# Generated by Django 4.2.7 on 2023-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('realizada', models.BooleanField(default=False)),
            ],
        ),
    ]
