# Generated by Django 4.2.7 on 2023-11-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
